name: Tests
on:
  push:
    branches:
      - main
      - Dev
  pull_request:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - id: step1
      run: echo "Welcome to the Github Actions workshop !"
